### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by R0rt1z2** [sloane-development/android_device_amazon_sloane#1]
- [x] Get boot menu working
- [x] Get ADB at boot
- [x] Get Permissive SELinux at boot
- [x] Reach bootanimation
- [x] Reach starting apps
- [x] Fix symbols
- [x] Boot the ROM
- [x] Fix Wi-Fi
- [x] Get bluetooth powering on
- [x] Fix Audio
- [x] Get bluetooth parinig devices
- [x] Fix media crash (external storage)
- [x] Fix Wifi-Direct
- [x] Fix SW decoding
- [x] ~~Fix themes crash~~ Themes are not prepared for Android TV UI, disable them.
- [ ] Fix HW decoding
- [ ] Fix OMX
- [ ] Fix NVRAM (long time booting)

**Comment by R0rt1z2** [comment]
Themes crash (wtf)?
```
W/SystemServer(  592): ***********************************************


F/SystemServer(  592): BOOT FAILURE Icon Mapping failed


F/SystemServer(  592): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference


F/SystemServer(  592): 	at com.android.server.ThemeService.removeObsoleteThemeOverlayIfExists(ThemeService.java:303)


F/SystemServer(  592): 	at com.android.server.ThemeService.systemRunning(ThemeService.java:263)


F/SystemServer(  592): 	at com.android.server.SystemServer$2.run(SystemServer.java:1380)


F/SystemServer(  592): 	at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:11587)


F/SystemServer(  592): 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1240)


F/SystemServer(  592): 	at com.android.server.SystemServer.run(SystemServer.java:285)


F/SystemServer(  592): 	at com.android.server.SystemServer.main(SystemServer.java:186)


F/SystemServer(  592): 	at java.lang.reflect.Method.invoke(Native Method)


F/SystemServer(  592): 	at java.lang.reflect.Method.invoke(Method.java:372)


F/SystemServer(  592): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)

F/SystemServer(  592): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by R0rt1z2** [comment]
Actually, Wi-Fi direct is fixed BUT there still some issues.
In order to pair the remote:
* If Wi-Fi is turned on, remote will not connect. You need to have Wi-Fi disabled, connect the remote and enable Wi-Fi again. (Same thing happens on FireOS, that's why they force you to pair the remote before connect to Wi-Fi)
* Remote doesn't reconnects after reboot.
* Some keys are useless (i.e: Alexa)

Will look deeper at the Wi-Fi direct.
